# Generated by Django 3.1.5 on 2021-01-06 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=8)),
                ('model', models.CharField(max_length=255)),
                ('service', models.DateField(blank=True, null=True)),
                ('technical_exam', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tripp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.projectmodel')),
                ('dirver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.employees')),
            ],
            options={
                'verbose_name': 'Fahrtenbuch',
                'verbose_name_plural': 'Fahrtenbucher',
            },
        ),
    ]
