# Generated by Django 3.1.5 on 2021-01-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cars_tripp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
